"""initial schema

Revision ID: e159073954d6
Revises: 
Create Date: 2026-06-10 16:10:07.684076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e159073954d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=32), nullable=True),
    sa.Column('plant_registry_number', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Enum('DOMESTIC', 'IMPORTED', name='productsource', native_enum=False, length=16), nullable=False),
    sa.Column('product_type', sa.Enum('WINE', 'DISTILLED_SPIRITS', 'MALT_BEVERAGE', name='producttype', native_enum=False, length=24), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('fanciful_name', sa.String(length=255), nullable=True),
    sa.Column('class_type', sa.String(length=255), nullable=True),
    sa.Column('alcohol_content_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alcohol_content_text', sa.String(length=64), nullable=True),
    sa.Column('net_contents', sa.String(length=64), nullable=True),
    sa.Column('name_and_address', sa.Text(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=128), nullable=True),
    sa.Column('appellation', sa.String(length=128), nullable=True),
    sa.Column('vintage', sa.String(length=8), nullable=True),
    sa.Column('formula', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_serial_number'), 'applications', ['serial_number'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batchstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('image_ref', sa.String(length=512), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='submissionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_application_id'), 'submissions', ['application_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_table('batch_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'position', name='uq_batch_item_position'),
    sa.UniqueConstraint('submission_id', name='uq_batch_item_submission')
    )
    op.create_index(op.f('ix_batch_items_batch_id'), 'batch_items', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_items_batch_id'), table_name='batch_items')
    op.drop_table('batch_items')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_application_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_applications_serial_number'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
