/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description Newest-first audit trail, optionally scoped to one submission.
         */
        get: operations["list_events_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe.
         *
         *     Exposed at the bare ``/health`` for the container healthcheck (which hits the
         *     backend directly) and under ``/api/health`` so the browser can reach it via
         *     the same ``/api`` reverse-proxy that fronts every other endpoint.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Submissions
         * @description Most recent submissions, newest first.
         */
        get: operations["list_submissions_api_submissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue Stats
         * @description Queue counts: pending, flagged for judgment, cleared this week, avg scan.
         */
        get: operations["queue_stats_api_submissions_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission
         * @description One submission with its persisted verification result.
         */
        get: operations["get_submission_api_submissions__submission_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Decision
         * @description Record the reviewer's judgment; idempotent overwrite is allowed.
         */
        post: operations["record_decision_api_submissions__submission_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission Image
         * @description The first stored label image (legacy single-image clients).
         */
        get: operations["get_submission_image_api_submissions__submission_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{submission_id}/images/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Submission Image At
         * @description One image of the submission's label set, by display order.
         */
        get: operations["get_submission_image_at_api_submissions__submission_id__images__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify
         * @description Verify a filing's label image set against its expected application data.
         *
         *     Accepts the full set of label images a COLA carries (repeated ``images``
         *     parts) — the mandatory content is split across them (warning on the back,
         *     ABV on the front) — or a single ``image`` for older clients. Fields merge
         *     on best verdict across the set; the result records which image each
         *     verdict came from.
         */
        post: operations["verify_api_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe.
         *
         *     Exposed at the bare ``/health`` for the container healthcheck (which hits the
         *     backend directly) and under ``/api/health`` so the browser can reach it via
         *     the same ``/api`` reverse-proxy that fronts every other endpoint.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditEventRow
         * @description One audit-log entry as returned by the API.
         */
        AuditEventRow: {
            /** Action */
            action: string;
            /** Actor */
            actor: string;
            /** Created At */
            created_at: string | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Submission Id */
            submission_id: number | null;
        };
        /** Body_verify_api_verify_post */
        Body_verify_api_verify_post: {
            /** Alcohol Content Pct */
            alcohol_content_pct?: number | null;
            /** Alcohol Content Text */
            alcohol_content_text?: string | null;
            /** Appellation */
            appellation?: string | null;
            /** Brand Name */
            brand_name: string;
            /** Class Type */
            class_type?: string | null;
            /** Country Of Origin */
            country_of_origin?: string | null;
            /** Fanciful Name */
            fanciful_name?: string | null;
            /**
             * Image
             * @description A single label image (older clients).
             */
            image?: string | null;
            /**
             * Images
             * @description The filing's label images in order (front, back, …).
             */
            images?: string[] | null;
            /** Name And Address */
            name_and_address?: string | null;
            /** Net Contents */
            net_contents?: string | null;
            /** @default distilled_spirits */
            product_type: components["schemas"]["ProductType"];
            /** Serial Number */
            serial_number?: string | null;
            /** @default domestic */
            source: components["schemas"]["ProductSource"];
            /** Vintage */
            vintage?: string | null;
        };
        /**
         * BoundingBox
         * @description Axis-aligned bounding box, derived from a detection polygon.
         *
         *     Most downstream logic (reading order, region matching) only needs an
         *     axis-aligned box; the original :attr:`TextLine.polygon` is kept for callers
         *     that care about rotation.
         */
        BoundingBox: {
            /** X Max */
            x_max: number;
            /** X Min */
            x_min: number;
            /** Y Max */
            y_max: number;
            /** Y Min */
            y_min: number;
        };
        /**
         * DecisionInput
         * @description The reviewer's decision plus an optional internal note.
         */
        DecisionInput: {
            decision: components["schemas"]["ReviewDecision"];
            /** Note */
            note?: string | null;
        };
        /**
         * FieldResult
         * @description One field's verification result — the per-field row of the contract.
         *
         *     ``field`` is the logical comparison key (matching the application columns
         *     and the corpus golden field keys): ``brand_name``, ``class_type``,
         *     ``alcohol_content``, ``net_contents``, ``name_and_address``,
         *     ``country_of_origin``, ``vintage``, … ``expected`` is the application value;
         *     ``found`` is what was recovered from the label (``None`` when nothing
         *     plausible was located). ``score`` is the comparison confidence/similarity in
         *     ``[0, 1]``. ``span``/``box`` locate the matched text for highlighting in the
         *     comparison UI.
         */
        FieldResult: {
            box?: components["schemas"]["BoundingBox"] | null;
            /** Expected */
            expected?: string | null;
            /** Field */
            field: string;
            /** Found */
            found?: string | null;
            /** Image Index */
            image_index?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            span?: components["schemas"]["SourceSpan"] | null;
            status: components["schemas"]["FieldStatus"];
        };
        /**
         * FieldStatus
         * @description Per-field outcome of comparing the label against the application.
         *
         *     String values match ``tests.corpus.schema.FieldVerdict`` and the fuzzy
         *     matcher's ``app.match.MatchStatus`` (which shares the first three), so a
         *     :class:`app.match.FieldMatch` maps straight onto a :class:`FieldResult`.
         *
         *     * ``MATCH`` — present and equivalent.
         *     * ``SOFT_WARNING`` — present but differing in a human-equivalent way (case /
         *       punctuation only) or a near miss worth a human glance.
         *     * ``MISMATCH`` — absent, or too different to be the same value.
         *     * ``NOT_CHECKED`` — the application did not supply this field, so there was
         *       nothing to verify against (does not affect the overall verdict).
         * @enum {string}
         */
        FieldStatus: "match" | "soft_warning" | "mismatch" | "not_checked";
        /**
         * GovernmentWarningResult
         * @description Result of verifying one label's Government Health Warning.
         *
         *     ``found_text`` is the located warning region (``None`` when no header was
         *     found). ``header_all_caps`` is ``None`` when there is no header to inspect.
         *     ``similarity`` is the wording match against :data:`GOVERNMENT_WARNING_TEXT`
         *     in ``[0, 1]`` (``0.0`` when missing). ``issues`` explains any non-compliance;
         *     ``limitations`` records what could not be checked from text alone.
         */
        GovernmentWarningResult: {
            box?: components["schemas"]["BoundingBox"] | null;
            /** Found Text */
            found_text?: string | null;
            /** Header All Caps */
            header_all_caps?: boolean | null;
            /** Image Index */
            image_index?: number | null;
            /** Issues */
            issues?: string[];
            /** Limitations */
            limitations?: string[];
            /**
             * Similarity
             * @default 0
             */
            similarity: number;
            span?: components["schemas"]["SourceSpan"] | null;
            verdict: components["schemas"]["WarningVerdict"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageQuality
         * @description How readable the uploaded image was, for retake guidance in the UI.
         */
        ImageQuality: {
            /**
             * Level
             * @enum {string}
             */
            level: "ok" | "low";
            /** Mean Confidence */
            mean_confidence: number;
            /** Message */
            message?: string | null;
            /** Text Regions */
            text_regions: number;
        };
        /**
         * OverallVerdict
         * @description Roll-up verdict for a whole label, surfaced to the agent.
         *
         *     Mirrors ``tests.corpus.schema.OverallVerdict``. ``WARNING`` is the engine's
         *     name for the "needs review" middle state: the label is plausibly fine but
         *     something (a soft field warning) warrants a human glance before approval.
         * @enum {string}
         */
        OverallVerdict: "pass" | "warning" | "fail";
        /**
         * ProductSource
         * @description Origin of the product, per TTB form 5100.31 (OMB 1513-0020).
         * @enum {string}
         */
        ProductSource: "domestic" | "imported";
        /**
         * ProductType
         * @description Class of alcohol beverage governed by TTB labeling rules.
         * @enum {string}
         */
        ProductType: "wine" | "distilled_spirits" | "malt_beverage";
        /**
         * QueueStats
         * @description Counts for the stat cards above the queue.
         */
        QueueStats: {
            /** Cleared Week */
            cleared_week: number;
            /** Flagged */
            flagged: number;
            /** Median Scan Ms */
            median_scan_ms: number | null;
            /** Pending */
            pending: number;
        };
        /**
         * ReviewDecision
         * @description The reviewer's judgment on a verified label.
         * @enum {string}
         */
        ReviewDecision: "approve" | "request_changes" | "request_info";
        /**
         * SourceSpan
         * @description Where a candidate was found in the OCR output.
         *
         *     ``line_index`` indexes :attr:`app.ocr.schemas.OcrResult.lines` (``None`` when
         *     a rule was run over a bare string with no line context). ``start``/``end``
         *     are character offsets into that line's text, so callers can highlight the
         *     exact substring that matched.
         */
        SourceSpan: {
            /** End */
            end: number;
            /** Line Index */
            line_index?: number | null;
            /** Start */
            start: number;
        };
        /**
         * SubmissionDetail
         * @description Full submission: the persisted verification result and application.
         */
        SubmissionDetail: {
            /** Applicant */
            applicant: string | null;
            /** Application */
            application: {
                [key: string]: unknown;
            } | null;
            /** Brand Name */
            brand_name: string | null;
            /** Class Type */
            class_type: string | null;
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at: string | null;
            decision: components["schemas"]["ReviewDecision"] | null;
            /** Decision Note */
            decision_note: string | null;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /** Image Filename */
            image_filename: string | null;
            /** Images */
            images?: components["schemas"]["SubmissionImageRow"][];
            /** Overall */
            overall: string | null;
            /** Processing Ms */
            processing_ms: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            status: components["schemas"]["SubmissionStatus"];
            /** Warning Verdict */
            warning_verdict: string | null;
        };
        /**
         * SubmissionImageRow
         * @description One image of the submission's label set (``index`` = display order).
         */
        SubmissionImageRow: {
            /** Filename */
            filename: string | null;
            /** Index */
            index: number;
            /** Kind */
            kind: string | null;
        };
        /**
         * SubmissionRow
         * @description One queue row: enough to render the table without the full result.
         */
        SubmissionRow: {
            /** Applicant */
            applicant: string | null;
            /** Brand Name */
            brand_name: string | null;
            /** Class Type */
            class_type: string | null;
            /** Created At */
            created_at: string | null;
            /** Decided At */
            decided_at: string | null;
            decision: components["schemas"]["ReviewDecision"] | null;
            /** Id */
            id: number;
            /** Image Filename */
            image_filename: string | null;
            /** Overall */
            overall: string | null;
            /** Processing Ms */
            processing_ms: number | null;
            status: components["schemas"]["SubmissionStatus"];
            /** Warning Verdict */
            warning_verdict: string | null;
        };
        /**
         * SubmissionStatus
         * @description Lifecycle of a single label verification job.
         * @enum {string}
         */
        SubmissionStatus: "pending" | "processing" | "completed" | "failed";
        /**
         * TimingInfo
         * @description Where the wall-clock time went, so agents can see the 5s budget holding.
         */
        TimingInfo: {
            /** Ocr Ms */
            ocr_ms: number;
            /** Total Ms */
            total_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerdictSummary
         * @description Counts of per-field statuses — a quick at-a-glance roll-up for the UI.
         */
        VerdictSummary: {
            /**
             * Match
             * @default 0
             */
            match: number;
            /**
             * Mismatch
             * @default 0
             */
            mismatch: number;
            /**
             * Not Checked
             * @default 0
             */
            not_checked: number;
            /**
             * Soft Warning
             * @default 0
             */
            soft_warning: number;
        };
        /**
         * VerificationImageInfo
         * @description One image of the verified filing, with its readability grade.
         */
        VerificationImageInfo: {
            /** Filename */
            filename: string | null;
            /** Index */
            index: number;
            quality: components["schemas"]["ImageQuality"];
        };
        /**
         * VerificationResponse
         * @description The API response for one verification (a filing's full label set).
         *
         *     ``image_filename`` mirrors the first image for older clients; ``images``
         *     lists every uploaded label with its per-image readability. The result's
         *     fields carry ``image_index`` into this list.
         */
        VerificationResponse: {
            /** Application Id */
            application_id: number | null;
            /** Image Filename */
            image_filename: string | null;
            image_quality: components["schemas"]["ImageQuality"];
            /** Images */
            images: components["schemas"]["VerificationImageInfo"][];
            result: components["schemas"]["VerificationResult"];
            status: components["schemas"]["SubmissionStatus"];
            /** Submission Id */
            submission_id: number;
            timing: components["schemas"]["TimingInfo"];
        };
        /**
         * VerificationResult
         * @description The complete verification output for one label: the stable JSON contract.
         *
         *     This is what is persisted to ``Submission.result`` and rendered by the
         *     comparison UI / batch results. It bundles the overall roll-up, every
         *     per-field result, the dedicated Government Health Warning result (kept
         *     separate because it carries its own verdict vocabulary), a status summary,
         *     and a human-readable rationale for the overall verdict.
         */
        VerificationResult: {
            /** Fields */
            fields?: components["schemas"]["FieldResult"][];
            government_warning: components["schemas"]["GovernmentWarningResult"];
            overall: components["schemas"]["OverallVerdict"];
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Schema Version
             * @default 2
             */
            schema_version: number;
            summary: components["schemas"]["VerdictSummary"];
        };
        /**
         * WarningVerdict
         * @description Outcome of the Government Health Warning check.
         *
         *     Mirrors ``tests.corpus.schema.WarningVerdict`` (the golden-data enum) so the
         *     verifier's output can be compared directly against the corpus expectations.
         * @enum {string}
         */
        WarningVerdict: "compliant" | "altered" | "missing";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                submission_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_submissions_api_submissions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_stats_api_submissions_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueStats"];
                };
            };
        };
    };
    get_submission_api_submissions__submission_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_decision_api_submissions__submission_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_image_api_submissions__submission_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_image_at_api_submissions__submission_id__images__index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: number;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_verify_api_verify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
